spring:

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    order: 0

  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mariadb://localhost:3306/escape
    username: root
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver

  devtools:
    livereload:
      enabled: true

mybatis:
  type-aliases-package: com.escapepj.demo
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.escapepj.demo
# type handler: mybatis가 query 결과를 Java 갹체로 바꿔줄 때 쓰는 녀석
#  type-handlers-package: 내가 따로, type hander를 만들 일이 있다. 그거 만들어서 저 패키지에 넣어두었으니, 가져다가 잘 써주세요.